apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-platform-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-531/repos
    targetRevision: 5.4.0+20260210.092002.50
    chart: cpd-platform
    helm:
      valuesObject:
        global:
          licenseAccept: true
          releaseVersion: 5.3.1
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          # imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:1ab24a2e3a2c52fd6f0f2a2a5faf11459f1196b9d29b2034488718a6a605094b
          installConfigImageName: cp/cpd/olm-utils-premium-v4
          installConfigImagePullPrefix: cp.icr.io
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
